version: '3.8'

services:
  app:
    image: phc9/app-with-actions:latest
    container_name: spring-server
    restart: always
    environment:
      APP_NAME: ${APP_NAME}
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 80:${SERVER_PORT}
