name: CD - Deploy to EC2

on:
   workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Docker Image on EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script_stop: true
        script: |
          docker pull dockerlecturer/app-with-actions:latest
          docker stop app-container || true
          docker rm app-container || true
          docker run -d \
            --name app-container \
            -p 80:8080 \
            --env SPRING_PROFILES_ACTIVE=prod \
            dockerlecturer/app-with-actions:latest
